import { kindSingular, openDetail, setMode, ui } from "../../lib/app";
import { toneVar } from "../../lib/format";
import { shallowEqual, useStore } from "../../lib/store";
import { ide, isLive, liveParts, openFile, openSourceOf, quickFix } from "../../lib/ide";
import type { Diag } from "../../lib/types";
import { keyLabel } from "./Ide";

const boxSev = (s: string) => (s === "error" ? "error" : s === "warning" ? "warning" : "info");

export function Inspector() {
  const active = useStore(ide, (s) => s.active);
  if (!active) return <div className="ide-insp"><div className="ide-sec"><span className="lab">Resource</span><span className="mu">No file is open.</span></div></div>;
  if (isLive(active)) return <LiveInspector id={active} />;
  return <FileInspector path={active} />;
}

function LiveInspector({ id }: { id: string }) {
  const ctx = useStore(ui, (s) => s.cluster?.context ?? "");
  const [kind, ns, name] = liveParts(id);
  return (
    <div className="ide-insp">
      <div className="ide-sec">
        <span className="lab">Resource</span>
        <div className="flex" style={{ alignItems: "baseline" }}><span className="kindtag">{kindSingular(kind)}</span><b className="ell">{name}</b></div>
        <span className="small mu">{ns ? `Namespace ${ns} · ` : ""}{ctx}</span>
      </div>
      <div className="ide-sec">
        <span className="lab">Source</span>
        <span className="mu" style={{ lineHeight: 1.45 }}>You are viewing the live object. Edit the file in the workspace that defines it.</span>
        <div className="flex">
          <button className="btn xs" onClick={() => void openSourceOf(kindSingular(kind), ns, name)}>Open source file</button>
          <button className="btn xs" onClick={() => {
            setMode("cluster");
            openDetail({ kind, ns, name });
          }}>Open in Cluster ↗</button>
        </div>
      </div>
    </div>
  );
}

function FileInspector({ path }: { path: string }) {
  const r = useStore(ide, (s) => s.inspect);
  const ctx = useStore(ui, (s) => s.cluster?.context ?? "no context");
  const line = useStore(ide, (s) => s.cur.line);
  const lineDiags = useStore(ide, (s) => (s.diags[path] ?? []).filter((d) => d.line === s.cur.line), shallowEqual);
  const mac = useStore(ui, (s) => s.platform === "darwin");
  void line;
  if (!r) return <div className="ide-insp"><div className="ide-sec"><span className="lab">Resource</span><span className="spinner" /></div></div>;
  const f = r.field;
  return (
    <div className="ide-insp">
      <div className="ide-sec" style={{ gap: 4 }}>
        <span className="lab">Resource{r.docs > 1 ? ` · document ${r.doc + 1} of ${r.docs}` : ""}</span>
        <div className="flex" style={{ alignItems: "baseline" }}>
          {r.kind && <span className="kindtag" style={{ flex: "none" }}>{r.kind}</span>}
          <b className="ell">{r.name || path}</b>
        </div>
        {r.where && <span className="small mu" style={{ lineHeight: 1.45, wordBreak: "break-word" }}>{r.where}</span>}
      </div>
      {r.kust && (
        <div className="ide-sec">
          <span className="lab">{r.renderErr ? "kustomize build fails" : `Builds ${r.renders?.length ?? 0} ${r.renders?.length === 1 ? "object" : "objects"}`}</span>
          {r.renderErr && <div className="errbox">{r.renderErr}</div>}
          {(r.renders ?? []).map((x, i) => (
            <div key={i} className="ide-render" title={x.path ? `${x.path}` : "Generated by kustomize"} onClick={() => x.path && void openFile(x.path)}>
              <span className="k">{x.kind}</span>
              <span className="ell">{x.name}</span>
              {x.ns && <span className="mono fa small ell" style={{ marginLeft: "auto" }}>{x.ns}</span>}
            </div>
          ))}
        </div>
      )}
      <div className="ide-sec" style={{ gap: 8 }}>
        <div className="flex">
          <span className="lab grow">On {ctx}</span>
          {r.live?.found && r.ref && (
            <a href="#" className="small" onClick={(e) => {
              e.preventDefault();
              setMode("cluster");
              openDetail({ kind: r.live!.kind, ns: r.ref!.ns, name: r.ref!.name });
            }}>Open in Cluster ↗</a>
          )}
        </div>
        {!r.live?.found && <span className="mu" style={{ lineHeight: 1.45 }}>{r.liveMsg || "No live object."}</span>}
        {r.live?.found && (
          <>
            <div className="kv ide-kv" style={{ display: "grid", gridTemplateColumns: "auto 1fr", gap: "4px 12px", fontSize: "calc(12px * var(--zf))" }}>
              {r.live.status && <><span className="fa">Status</span><span className="mono" style={{ color: toneVar(r.live.tone, "var(--tx)") }}>{r.live.status}</span></>}
              {r.live.rows.filter((kv) => kv.k !== "Status").map((kv) => (
                <span key={kv.k} style={{ display: "contents" }}>
                  <span className="fa">{kv.k}</span>
                  <span className="mono" style={{ fontSize: "calc(11.5px * var(--zf))", color: toneVar(kv.t, "var(--tx)"), wordBreak: "break-all" }}>{kv.v}</span>
                </span>
              ))}
            </div>
            {r.live.pods.map((p) => (
              <div key={p.name} className="flex" style={{ fontSize: "calc(11.5px * var(--zf))" }}>
                <span className="dot sm" style={{ background: toneVar(p.tone, "var(--ok)") }} />
                <span className="mono ell grow">{p.name}</span>
                <span style={{ color: toneVar(p.tone, "var(--mu)"), whiteSpace: "nowrap" }}>{p.status}</span>
              </div>
            ))}
            {r.live.manager && <span className="small mu">Managed by {r.live.manager}</span>}
            {r.live.event && <div className="ide-box error">{r.live.event}</div>}
            {r.drift > 0 && (
              <div className="ide-box warning">
                <span>This file differs from the live object ({r.drift} lines). Apply to sync it, or review the diff.</span>
                <button className="btn xs" style={{ alignSelf: "flex-start", background: "var(--p1)" }} onClick={() => ide.set((s) => ({ modes: { ...s.modes, [path]: "live" } }))}>Show diff</button>
              </div>
            )}
          </>
        )}
      </div>
      <div className="ide-sec">
        <span className="lab">Field at cursor</span>
        {f ? (
          <>
            <span className="mono ac" style={{ fontSize: "calc(11px * var(--zf))", wordBreak: "break-all", lineHeight: 1.5 }}>{f.path}</span>
            {f.type && <span className="mono mu" style={{ fontSize: "calc(11px * var(--zf))" }}>{f.type}</span>}
            {f.doc ? <span style={{ lineHeight: 1.5 }}>{f.doc}</span> : <span className="mu" style={{ lineHeight: 1.5 }}>{r.schema === "No schema" || !r.schema ? "The schema of this API version is not loaded." : "The schema has no description for this field."}</span>}
            {f.hasLive && (
              <div style={{ display: "grid", gridTemplateColumns: "auto 1fr", gap: "3px 12px", fontSize: "calc(11.5px * var(--zf))", marginTop: 2 }}>
                <span className="fa">This file</span><span className="mono" style={{ wordBreak: "break-all" }}>{f.value || "—"}</span>
                <span className="fa">Live</span><span className="mono" style={{ color: f.same ? "var(--tx)" : "var(--wa)", wordBreak: "break-all" }}>{f.live}</span>
              </div>
            )}
          </>
        ) : (
          <span className="mu" style={{ lineHeight: 1.45 }}>Put the cursor on a field to see its schema and its live value.</span>
        )}
        {lineDiags.map((d, i) => <LineDiag key={i} path={path} d={d} mac={mac} />)}
      </div>
    </div>
  );
}

function LineDiag({ path, d, mac }: { path: string; d: Diag; mac: boolean }) {
  return (
    <div className={"ide-box " + boxSev(d.sev)} style={{ marginTop: 4 }}>
      <span>{d.msg}{d.live && <span className="ide-badge">from cluster</span>}</span>
      {d.fix && (
        <button className="btn xs primary ide-fix" onClick={() => void quickFix(path, d)}>
          {d.fix}<span className="kbd" style={{ color: "inherit", opacity: 0.7 }}>{keyLabel(mac, ".")}</span>
        </button>
      )}
    </div>
  );
}
